//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM_TRUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIEM_TRUONG()
        {
            this.LOPs = new HashSet<LOP>();
        }
    
        public decimal ID { get; set; }
        public Nullable<int> MA_NAM_HOC { get; set; }
        public string MA_SO_GD { get; set; }
        public Nullable<decimal> ID_PHONG_GD { get; set; }
        public string MA_PHONG_GD { get; set; }
        public decimal ID_TRUONG { get; set; }
        public string MA_TRUONG { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public string DIEN_THOAI { get; set; }
        public string DIA_CHI { get; set; }
        public Nullable<double> KHOANG_CACH_DIEM_TRUONG_CHINH { get; set; }
        public string PHUONG_TIEN_CO_THE_DI_LAI { get; set; }
        public Nullable<double> DIEN_TICH { get; set; }
    
        public virtual NAM_HOC NAM_HOC { get; set; }
        public virtual PHONG_GD PHONG_GD { get; set; }
        public virtual SO_GD SO_GD { get; set; }
        public virtual TRUONG TRUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOPs { get; set; }
    }
}
