//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHIEM_VU_KIEM_NHIEM
    {
        public string MA { get; set; }
        public string TEN { get; set; }
        public Nullable<int> IS_CB { get; set; }
        public Nullable<int> IS_GV { get; set; }
        public Nullable<int> IS_NV { get; set; }
        public Nullable<int> IS_MN { get; set; }
        public Nullable<int> IS_C1 { get; set; }
        public Nullable<int> IS_C2 { get; set; }
        public Nullable<int> IS_C3 { get; set; }
        public Nullable<int> IS_GDTX { get; set; }
        public Nullable<int> THU_TU { get; set; }
        public Nullable<decimal> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<decimal> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
    }
}
