//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NGOAI_NGU_HS_NHAN_SU
    {
        public int ID { get; set; }
        public Nullable<decimal> ID_NHAN_SU { get; set; }
        public string MA_NGOAI_NGU { get; set; }
        public string MA_TRINH_DO_NGOAI_NGU { get; set; }
        public Nullable<decimal> DIEM_NGOAI_NGU { get; set; }
        public Nullable<System.DateTime> NGAY_CAP { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual NHAN_SU NHAN_SU { get; set; }
    }
}
