//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOC_SINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOC_SINH()
        {
            this.SUC_KHOE_NUOI_DUONG = new HashSet<SUC_KHOE_NUOI_DUONG>();
            this.TONG_KET_C1 = new HashSet<TONG_KET_C1>();
            this.TONG_KET = new HashSet<TONG_KET>();
        }
    
        public decimal ID { get; set; }
        public string MA_SO_GD { get; set; }
        public Nullable<decimal> ID_PHONG_GD { get; set; }
        public string MA_PHONG_GD { get; set; }
        public Nullable<decimal> ID_TRUONG { get; set; }
        public string MA_TRUONG { get; set; }
        public int MA_NAM_HOC { get; set; }
        public string MA_CAP_HOC { get; set; }
        public string MA_KHOI { get; set; }
        public Nullable<decimal> ID_LOP { get; set; }
        public string MA_LOP { get; set; }
        public string MA { get; set; }
        public string HO_TEN { get; set; }
        public string HO_DEM { get; set; }
        public string TEN_DEM { get; set; }
        public string TEN { get; set; }
        public string TEN_TAT { get; set; }
        public System.DateTime NGAY_SINH { get; set; }
        public string CMND { get; set; }
        public string NOI_CAP { get; set; }
        public Nullable<System.DateTime> NGAY_CAP { get; set; }
        public string MA_GIOI_TINH { get; set; }
        public string MA_DAN_TOC { get; set; }
        public string MA_QUOC_TICH { get; set; }
        public string MA_KHU_VUC { get; set; }
        public string MA_NHOM_MAU { get; set; }
        public string MA_MIEN_GIAM_HOC_PHI { get; set; }
        public string MA_LOAI_KHUYET_TAT { get; set; }
        public string MA_TINH { get; set; }
        public Nullable<decimal> ID_HUYEN { get; set; }
        public string MA_HUYEN { get; set; }
        public Nullable<decimal> ID_XA { get; set; }
        public string MA_XA { get; set; }
        public string THON_XOM { get; set; }
        public string NOI_SINH { get; set; }
        public string CHO_O_HIEN_NAY { get; set; }
        public string TEN_CHA { get; set; }
        public string NGHE_NGHIEP_CHA { get; set; }
        public string TEN_ME { get; set; }
        public string NGHE_NGHIEP_ME { get; set; }
        public string TEN_NGUOI_DD { get; set; }
        public string NGHE_NGHIEP_NGUOI_DD { get; set; }
        public string DIEN_THOAI_LIEN_HE { get; set; }
        public Nullable<int> IS_KHUYET_TAT_KHONG_DANH_GIA { get; set; }
        public Nullable<int> IS_DOAN_VIEN { get; set; }
        public Nullable<int> IS_DOI_VIEN { get; set; }
        public Nullable<int> IS_HOC_SINH_BAN_TRU_DAN_NUOI { get; set; }
        public Nullable<int> IS_HOC_SINH_TIENG_DAN_TOC { get; set; }
        public Nullable<int> IS_HOC_2_BUOI { get; set; }
        public Nullable<int> IS_HOC_SONG_NGU { get; set; }
        public Nullable<int> IS_HO_NGHEO { get; set; }
        public Nullable<int> IS_VUNG_KK { get; set; }
        public Nullable<int> IS_ME_DT { get; set; }
        public Nullable<int> IS_CHA_DT { get; set; }
        public Nullable<int> IS_LUU_BAN_NAM_TRUOC { get; set; }
        public string MA_TRANG_THAI_K1 { get; set; }
        public string MA_TRANG_THAI_K2 { get; set; }
        public string MA_TRANG_THAI_HIEN_TAI { get; set; }
        public Nullable<System.DateTime> NGAY_TRANG_THAI { get; set; }
        public string MA_LY_DO_THOI_HOC { get; set; }
        public string MA_DIEN_CHINH_SACH { get; set; }
        public Nullable<decimal> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<decimal> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<int> THU_TU { get; set; }
        public string URL_ANH_DAI_DIEN { get; set; }
        public Nullable<int> NAM_SINH_CHA { get; set; }
        public Nullable<int> NAM_SINH_ME { get; set; }
        public Nullable<int> NAM_SINH_NGUOI_DO_DAU { get; set; }
        public string DAN_TOC_THEO_GIAY_KHAI_SINH { get; set; }
        public string MA_HINH_THUC_HOC_TAP { get; set; }
        public Nullable<int> IS_HOC_SINH_NTRU_DAN_NUOI { get; set; }
        public string MA_LOP_GHEP { get; set; }
        public Nullable<int> IS_KY_NANG_SONG { get; set; }
        public Nullable<int> IS_HOC_SINH_DT_TRO_GIANG { get; set; }
        public Nullable<int> IS_HOC_SINH_PT_DT_BTRU { get; set; }
        public Nullable<int> IS_HOC_SINH_LOP_BTRU { get; set; }
        public Nullable<int> IS_NHU_CAU_HO_TRO_NNGU { get; set; }
        public Nullable<int> IS_TANG_CUONG_TVIET { get; set; }
        public Nullable<bool> IS_HOAN_THANH_CHUONG_TRINH_MAM_NON { get; set; }
        public string MA_CONG_DAN { get; set; }
        public string MA_LOP_HUONG_NGHIEP_DAY_NGHE { get; set; }
        public string MA_IMPORT { get; set; }
    
        public virtual DM_CAP_HOC DM_CAP_HOC { get; set; }
        public virtual DM_GIOI_TINH DM_GIOI_TINH { get; set; }
        public virtual DM_TINH DM_TINH { get; set; }
        public virtual DM_XA DM_XA { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual NAM_HOC NAM_HOC { get; set; }
        public virtual PHONG_GD PHONG_GD { get; set; }
        public virtual SO_GD SO_GD { get; set; }
        public virtual TRUONG TRUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUC_KHOE_NUOI_DUONG> SUC_KHOE_NUOI_DUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONG_KET_C1> TONG_KET_C1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONG_KET> TONG_KET { get; set; }
    }
}
