//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOC_SINH_TOT_NGHIEP
    {
        public decimal ID { get; set; }
        public string MA_SO_GD { get; set; }
        public Nullable<decimal> ID_PHONG_GD { get; set; }
        public string MA_PHONG_GD { get; set; }
        public Nullable<decimal> ID_TRUONG { get; set; }
        public string MA_TRUONG { get; set; }
        public int MA_NAM_HOC { get; set; }
        public string MA_CAP_HOC { get; set; }
        public Nullable<decimal> ID_HOC_SINH { get; set; }
        public Nullable<decimal> ID_LOP { get; set; }
        public string MA_LOP { get; set; }
        public string TEN_LOP { get; set; }
        public string MA { get; set; }
        public string HO_TEN { get; set; }
        public string HO_DEM { get; set; }
        public string TEN { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public string MA_GIOI_TINH { get; set; }
        public string MA_DAN_TOC { get; set; }
        public string NOI_SINH { get; set; }
        public string CHO_O_HIEN_NAY { get; set; }
        public string HUONG_KK { get; set; }
        public Nullable<double> DIEM_VAN { get; set; }
        public Nullable<double> DIEM_TOAN { get; set; }
        public Nullable<double> DIEM_NGOAI_NGU { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<int> IS_TOT_NGHIEP { get; set; }
        public string MA_LOAI_TOT_NGHIEP { get; set; }
    
        public virtual DM_GIOI_TINH DM_GIOI_TINH { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual NAM_HOC NAM_HOC { get; set; }
        public virtual PHONG_GD PHONG_GD { get; set; }
        public virtual SO_GD SO_GD { get; set; }
        public virtual TRUONG TRUONG { get; set; }
        public virtual DM_DAN_TOC DM_DAN_TOC { get; set; }
    }
}
