//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP()
        {
            this.LOP_MON = new HashSet<LOP_MON>();
            this.HOC_SINH = new HashSet<HOC_SINH>();
            this.HOC_SINH_TOT_NGHIEP = new HashSet<HOC_SINH_TOT_NGHIEP>();
            this.TONG_KET_C1 = new HashSet<TONG_KET_C1>();
            this.TONG_KET = new HashSet<TONG_KET>();
            this.SUC_KHOE_NUOI_DUONG = new HashSet<SUC_KHOE_NUOI_DUONG>();
        }
    
        public decimal ID { get; set; }
        public string MA_SO_GD { get; set; }
        public Nullable<decimal> ID_PHONG_GD { get; set; }
        public string MA_PHONG_GD { get; set; }
        public Nullable<decimal> ID_TRUONG { get; set; }
        public string MA_TRUONG { get; set; }
        public string MA { get; set; }
        public int MA_NAM_HOC { get; set; }
        public string MA_CAP_HOC { get; set; }
        public Nullable<decimal> ID_DIEM_TRUONG { get; set; }
        public string MA_DIEM_TRUONG { get; set; }
        public string MA_GIAO_VIEN_CHU_NHIEM { get; set; }
        public string MA_HINH_THUC_DAO_TAO_HOC_TAP { get; set; }
        public string MA_KIEU_LOP { get; set; }
        public string MA_LOP_DAO_TAO_BOI_DUONG { get; set; }
        public string MA_LOP_HUONG_NGHIEP_DAY_NGHE { get; set; }
        public string MA_KHOI { get; set; }
        public string MA_PHAN_BAN { get; set; }
        public string MA_DANH_MUC_TIET_HOC { get; set; }
        public string MA_DANH_MUC_NGOAI_NGU { get; set; }
        public string TEN { get; set; }
        public Nullable<int> IS_DAY_2_BUOI_NGAY { get; set; }
        public Nullable<int> IS_LOP_CHUYEN { get; set; }
        public Nullable<int> IS_LOP_GHEP { get; set; }
        public Nullable<int> IS_BAN_TRU { get; set; }
        public Nullable<int> IS_HOC_5_BUOI_TUAN { get; set; }
        public Nullable<int> IS_HOC_6_8_BUOI_TUAN { get; set; }
        public Nullable<int> IS_HOC_9_10_BUOI_TUAN { get; set; }
        public Nullable<int> IS_TBDH_TVIET { get; set; }
        public Nullable<int> IS_TBDH_TOAN { get; set; }
        public Nullable<int> IS_DAI_DIEN_CHA_ME_LOP { get; set; }
        public Nullable<int> IS_DAI_DIEN_CHA_ME_TRUONG { get; set; }
        public Nullable<decimal> ID_GIAO_VIEN_CHU_NHIEM { get; set; }
        public Nullable<int> THU_TU { get; set; }
        public Nullable<decimal> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<decimal> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<int> TRANG_THAI { get; set; }
        public Nullable<int> IS_CO_HOC_SINH_HOC_NGHE { get; set; }
        public Nullable<int> IS_LOP_CHUYEN_BIET { get; set; }
        public Nullable<int> IS_LOP_CO_TRE_KHUYET_TAT { get; set; }
        public Nullable<int> ISVNEN { get; set; }
        public string MA_NHOM_TUOI_MN { get; set; }
        public string MA_HE_CHUYEN { get; set; }
        public Nullable<int> IS_LOP_GHEP_2_TUOI { get; set; }
        public Nullable<int> IS_LOP_GHEP_3_TUOI { get; set; }
        public string MA_DANH_MUC_NGOAI_NGU_2 { get; set; }
        public Nullable<int> IS_CTGDMN_MOI { get; set; }
        public Nullable<int> IS_CT_CSGD { get; set; }
        public string MA_SO_TIET_NGOAI_NGU { get; set; }
        public Nullable<decimal> ID_LOP_GHEP { get; set; }
    
        public virtual DM_CAP_HOC DM_CAP_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP_MON> LOP_MON { get; set; }
        public virtual DM_NHOM_TUOI_MN DM_NHOM_TUOI_MN { get; set; }
        public virtual DM_PHAN_BAN DM_PHAN_BAN { get; set; }
        public virtual DM_SO_TIET_NGOAI_NGU DM_SO_TIET_NGOAI_NGU { get; set; }
        public virtual DM_TIET_HOC DM_TIET_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_SINH> HOC_SINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_SINH_TOT_NGHIEP> HOC_SINH_TOT_NGHIEP { get; set; }
        public virtual NAM_HOC NAM_HOC { get; set; }
        public virtual PHONG_GD PHONG_GD { get; set; }
        public virtual SO_GD SO_GD { get; set; }
        public virtual TRUONG TRUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONG_KET_C1> TONG_KET_C1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONG_KET> TONG_KET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUC_KHOE_NUOI_DUONG> SUC_KHOE_NUOI_DUONG { get; set; }
        public virtual DIEM_TRUONG DIEM_TRUONG { get; set; }
    }
}
