//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP_MON
    {
        public decimal ID { get; set; }
        public int MA_NAM_HOC { get; set; }
        public string MA_SO_GD { get; set; }
        public Nullable<decimal> ID_PHONG_GD { get; set; }
        public string MA_PHONG_GD { get; set; }
        public decimal ID_TRUONG { get; set; }
        public string MA_TRUONG { get; set; }
        public decimal ID_LOP { get; set; }
        public Nullable<decimal> ID_MON_HOC { get; set; }
        public string MA_MON_HOC { get; set; }
        public int HOC_KY { get; set; }
        public Nullable<decimal> ID_GIAO_VIEN_BO_MON { get; set; }
        public string MA_GIAO_VIEN_BO_MON { get; set; }
        public Nullable<decimal> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<decimal> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<int> TRANG_THAI { get; set; }
    
        public virtual DM_MON_HOC DM_MON_HOC { get; set; }
        public virtual LOP LOP { get; set; }
    }
}
