//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_SU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAN_SU()
        {
            this.DM_NGOAI_NGU_HS_NHAN_SU = new HashSet<DM_NGOAI_NGU_HS_NHAN_SU>();
        }
    
        public decimal ID { get; set; }
        public string HO_TEN { get; set; }
        public string MA { get; set; }
        public string HO_TEN_KHAC { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public string NOI_SINH { get; set; }
        public string MA_CAP_DON_VI { get; set; }
        public string DAN_TOC_THEO_GIAY_KHAI_SINH { get; set; }
        public Nullable<int> MA_NAM_HOC { get; set; }
        public string MA_SO_GD { get; set; }
        public Nullable<decimal> ID_PHONG_GD { get; set; }
        public string MA_PHONG_GD { get; set; }
        public Nullable<decimal> ID_TRUONG { get; set; }
        public string MA_TRUONG { get; set; }
        public string MA_TINH { get; set; }
        public Nullable<decimal> ID_HUYEN { get; set; }
        public string MA_HUYEN { get; set; }
        public Nullable<decimal> ID_XA { get; set; }
        public string MA_XA { get; set; }
        public string MA_CAP_HOC { get; set; }
        public string QUE_QUAN { get; set; }
        public string DIA_CHI_THUONG_TRU { get; set; }
        public string NOI_O_HIEN_NAY { get; set; }
        public string NGHE_NGHIEP_KHI_DUOC_TUYEN_DUNG { get; set; }
        public Nullable<System.DateTime> NGAY_TUYEN_DUNG { get; set; }
        public string CO_QUAN_TUYEN_DUNG { get; set; }
        public string SO_CMTND { get; set; }
        public string NOI_CAP { get; set; }
        public Nullable<System.DateTime> NGAY_CAP { get; set; }
        public Nullable<int> IS_DANG_VIEN { get; set; }
        public Nullable<int> IS_DOAN_VIEN { get; set; }
        public Nullable<System.DateTime> NGAY_DANG_VIEN { get; set; }
        public Nullable<System.DateTime> NGAY_DANG_VIEN_CHINH_THUC { get; set; }
        public Nullable<System.DateTime> NGAY_DOAN_VIEN { get; set; }
        public string DANH_HIEU_DUOC_PHONG_TANG_CAO_NHAT { get; set; }
        public string SO_TRUONG_CONG_TAC { get; set; }
        public string SO_SO_BHXH { get; set; }
        public Nullable<System.DateTime> NGAY_BAT_DAU_BHXH { get; set; }
        public string MA_SO_THUE { get; set; }
        public Nullable<double> CHIEU_CAO { get; set; }
        public Nullable<double> CAN_NANG { get; set; }
        public Nullable<System.DateTime> NGAY_HUONG_LUONG { get; set; }
        public string HE_SO_LUONG { get; set; }
        public string NHAN_XET_DANH_GIA_CO_QUAN_DV { get; set; }
        public string URL_ANH_DAI_DIEN { get; set; }
        public string DI_DONG { get; set; }
        public string NGAN_HANG_MO_TK { get; set; }
        public string EMAIL { get; set; }
        public string SO_TAI_KHOAN { get; set; }
        public string MA_GIOI_TINH { get; set; }
        public string MA_DAN_TOC { get; set; }
        public string MA_TON_GIAO { get; set; }
        public string MA_NUOC { get; set; }
        public string MA_BAC_LUONG { get; set; }
        public Nullable<decimal> PHAN_TRAM_VUOT_KHUNG { get; set; }
        public string MA_NGACH { get; set; }
        public string MA_HOC_VAN_PHO_THONG { get; set; }
        public string MA_TRINH_DO_LLCT { get; set; }
        public string MA_TRINH_DO_QLGD { get; set; }
        public string MA_TRINH_DO_CHUYEN_MON { get; set; }
        public string MA_NGOAI_NGU { get; set; }
        public string MA_TRINH_DO_NGOAI_NGU { get; set; }
        public Nullable<decimal> DIEM_NGOAI_NGU { get; set; }
        public string MA_CHUYEN_MON_1 { get; set; }
        public string MA_CHUYEN_MON_2 { get; set; }
        public string MA_TRINH_DO_1 { get; set; }
        public string MA_TRINH_DO_2 { get; set; }
        public string MA_TRINH_DO_TIN_HOC { get; set; }
        public string MA_HINH_THUC_HOP_DONG { get; set; }
        public string MA_NHOM_MAU { get; set; }
        public string MA_THANH_PHAN_XUAT_THAN { get; set; }
        public string MA_CHUYEN_NGANH_DAO_TAO { get; set; }
        public string MA_THUONG_BINH { get; set; }
        public string MA_LOAI_CAN_BO { get; set; }
        public string MA_NHOM_CAN_BO { get; set; }
        public string MA_PHONG_BAN { get; set; }
        public Nullable<decimal> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<decimal> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<decimal> PC_THU_HUT { get; set; }
        public Nullable<decimal> PC_THAM_NIEN { get; set; }
        public Nullable<decimal> PC_UD_NGHE { get; set; }
        public Nullable<int> TRANG_THAI { get; set; }
        public Nullable<int> IS_TAP_HUAN_KY_NANG_SONG { get; set; }
        public string MA_LOAI_GV_GIANG_DAY_VAN_HOA { get; set; }
        public string MA_TRANG_THAI_CAN_BO { get; set; }
        public string MA_CONG_DAN { get; set; }
        public string MA_IMPORT { get; set; }
        public string MA_SO_NGACH { get; set; }
        public string MA_CHUC_VU_HIEN_TAI { get; set; }
        public Nullable<int> IS_DAY_1_BUOI { get; set; }
        public Nullable<int> IS_DAY_2_BUOI { get; set; }
        public string MA_MON_DAY { get; set; }
        public string MA_MON_KIEM_NHIEM { get; set; }
        public Nullable<int> IS_DAY_LOP_KHUYET_TAT { get; set; }
        public string MA_TIENG_DAN_TOC { get; set; }
        public Nullable<int> IS_DAY_TIENG_DAN_TOC { get; set; }
        public Nullable<int> IS_CHUYEN_TRACH_DOAN_DOI { get; set; }
        public Nullable<int> SO_TIET_THUC_DAY_TUAN { get; set; }
        public Nullable<int> SO_TIET_THUC_KIEM_NHIEM_TUAN { get; set; }
        public string MA_GIAO_VIEN_GIOI { get; set; }
        public string MA_BOI_DUONG_TX { get; set; }
        public string MA_KET_QUA_CHUAN_NGHE_NGHIEP { get; set; }
        public string MA_DG_VIEN_CHUC { get; set; }
        public string MA_CHUAN_DAO_TAO { get; set; }
        public string HO_TEN_KHONG_DAU { get; set; }
    
        public virtual DM_GIOI_TINH DM_GIOI_TINH { get; set; }
        public virtual DM_NGACH DM_NGACH { get; set; }
        public virtual DM_NGOAI_NGU DM_NGOAI_NGU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_NGOAI_NGU_HS_NHAN_SU> DM_NGOAI_NGU_HS_NHAN_SU { get; set; }
        public virtual DM_NHOM_CAN_BO DM_NHOM_CAN_BO { get; set; }
        public virtual DM_NHOM_MAU DM_NHOM_MAU { get; set; }
        public virtual DM_NUOC DM_NUOC { get; set; }
        public virtual DM_TINH DM_TINH { get; set; }
        public virtual DM_TON_GIAO DM_TON_GIAO { get; set; }
        public virtual DM_TRANG_THAI_CAN_BO DM_TRANG_THAI_CAN_BO { get; set; }
        public virtual DM_TRINH_DO_CHUYEN_MON_NGHIEP_VU DM_TRINH_DO_CHUYEN_MON_NGHIEP_VU { get; set; }
        public virtual DM_TRINH_DO_LLCT DM_TRINH_DO_LLCT { get; set; }
        public virtual DM_TRINH_DO_NGOAI_NGU DM_TRINH_DO_NGOAI_NGU { get; set; }
        public virtual DM_TRINH_DO_QLGD DM_TRINH_DO_QLGD { get; set; }
        public virtual DM_TRINH_DO_TIN_HOC DM_TRINH_DO_TIN_HOC { get; set; }
        public virtual DM_XA DM_XA { get; set; }
        public virtual NAM_HOC NAM_HOC { get; set; }
        public virtual PHONG_BAN PHONG_BAN { get; set; }
        public virtual PHONG_GD PHONG_GD { get; set; }
        public virtual SO_GD SO_GD { get; set; }
        public virtual TRUONG TRUONG { get; set; }
        public virtual DM_LOAI_CAN_BO DM_LOAI_CAN_BO { get; set; }
        public virtual DM_HINH_THUC_HOP_DONG DM_HINH_THUC_HOP_DONG { get; set; }
        public virtual DM_HUYEN DM_HUYEN { get; set; }
        public virtual DM_CHUYEN_MON DM_CHUYEN_MON { get; set; }
    }
}
