//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOM_QUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHOM_QUYEN()
        {
            this.PHONG_BAN = new HashSet<PHONG_BAN>();
        }
    
        public string MA { get; set; }
        public string TEN { get; set; }
        public string MA_CAP_DON_VI { get; set; }
        public string MA_CAP_HOC { get; set; }
        public string MA_SO_GD { get; set; }
        public string MA_PHONG_GD { get; set; }
        public string MA_TRUONG { get; set; }
        public Nullable<int> TRANG_THAI { get; set; }
        public Nullable<decimal> NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<decimal> NGUOI_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
    
        public virtual DM_CAP_HOC DM_CAP_HOC { get; set; }
        public virtual SO_GD SO_GD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONG_BAN> PHONG_BAN { get; set; }
    }
}
