//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONG_KET_C1
    {
        public decimal ID { get; set; }
        public int MA_NAM_HOC { get; set; }
        public string MA_SO_GD { get; set; }
        public Nullable<decimal> ID_PHONG_GD { get; set; }
        public string MA_PHONG_GD { get; set; }
        public Nullable<decimal> ID_TRUONG { get; set; }
        public string MA_TRUONG { get; set; }
        public string MA_CAP_HOC { get; set; }
        public string MA_KHOI { get; set; }
        public Nullable<decimal> ID_LOP { get; set; }
        public string MA_LOP { get; set; }
        public Nullable<decimal> ID_HOC_SINH { get; set; }
        public string MA_HOC_SINH { get; set; }
        public string THANH_TICH_DAC_BIET { get; set; }
        public string MA_DANH_HIEU { get; set; }
        public string NOI_DUNG_KHEN_THUONG { get; set; }
        public Nullable<int> IS_REN_LUYEN_LAI { get; set; }
        public string LY_DO_REN_LUYEN_LAI { get; set; }
        public Nullable<int> IS_GUI_HIEU_TRUONG_CHO_LEN_LOP { get; set; }
        public string TV_DGTX_GK1 { get; set; }
        public string TV_DGTX_CK1 { get; set; }
        public string TV_DGTX_GK2 { get; set; }
        public string TV_DGTX_CK2 { get; set; }
        public Nullable<int> TV_DIEM_GK1 { get; set; }
        public Nullable<int> TV_DIEM_CK1 { get; set; }
        public Nullable<int> TV_DIEM_GK2 { get; set; }
        public Nullable<int> TV_DIEM_CK2 { get; set; }
        public string TO_DGTX_GK1 { get; set; }
        public string TO_DGTX_CK1 { get; set; }
        public string TO_DGTX_GK2 { get; set; }
        public string TO_DGTX_CK2 { get; set; }
        public Nullable<int> TO_DIEM_GK1 { get; set; }
        public Nullable<int> TO_DIEM_CK1 { get; set; }
        public Nullable<int> TO_DIEM_GK2 { get; set; }
        public Nullable<int> TO_DIEM_CK2 { get; set; }
        public string TX_DGTX_GK1 { get; set; }
        public string TX_DGTX_CK1 { get; set; }
        public string TX_DGTX_GK2 { get; set; }
        public string TX_DGTX_CK2 { get; set; }
        public Nullable<int> TX_DIEM_GK1 { get; set; }
        public Nullable<int> TX_DIEM_CK1 { get; set; }
        public Nullable<int> TX_DIEM_GK2 { get; set; }
        public Nullable<int> TX_DIEM_CK2 { get; set; }
        public string NN_DGTX_GK1 { get; set; }
        public string NN_DGTX_CK1 { get; set; }
        public string NN_DGTX_GK2 { get; set; }
        public string NN_DGTX_CK2 { get; set; }
        public Nullable<int> NN_DIEM_GK1 { get; set; }
        public Nullable<int> NN_DIEM_CK1 { get; set; }
        public Nullable<int> NN_DIEM_GK2 { get; set; }
        public Nullable<int> NN_DIEM_CK2 { get; set; }
        public string TH_DGTX_GK1 { get; set; }
        public string TH_DGTX_CK1 { get; set; }
        public string TH_DGTX_GK2 { get; set; }
        public string TH_DGTX_CK2 { get; set; }
        public Nullable<int> TH_DIEM_GK1 { get; set; }
        public Nullable<int> TH_DIEM_CK1 { get; set; }
        public Nullable<int> TH_DIEM_GK2 { get; set; }
        public Nullable<int> TH_DIEM_CK2 { get; set; }
        public string DT_DGTX_GK1 { get; set; }
        public string DT_DGTX_CK1 { get; set; }
        public string DT_DGTX_GK2 { get; set; }
        public string DT_DGTX_CK2 { get; set; }
        public Nullable<int> DT_DIEM_GK1 { get; set; }
        public Nullable<int> DT_DIEM_CK1 { get; set; }
        public Nullable<int> DT_DIEM_GK2 { get; set; }
        public Nullable<int> DT_DIEM_CK2 { get; set; }
        public string DD_DGTX_GK1 { get; set; }
        public string DD_DGTX_CK1 { get; set; }
        public string DD_DGTX_GK2 { get; set; }
        public string DD_DGTX_CK2 { get; set; }
        public string AN_DGTX_GK1 { get; set; }
        public string AN_DGTX_CK1 { get; set; }
        public string AN_DGTX_GK2 { get; set; }
        public string AN_DGTX_CK2 { get; set; }
        public string MT_DGTX_GK1 { get; set; }
        public string MT_DGTX_CK1 { get; set; }
        public string MT_DGTX_GK2 { get; set; }
        public string MT_DGTX_CK2 { get; set; }
        public string TC_DGTX_GK1 { get; set; }
        public string TC_DGTX_CK1 { get; set; }
        public string TC_DGTX_GK2 { get; set; }
        public string TC_DGTX_CK2 { get; set; }
        public string TD_DGTX_GK1 { get; set; }
        public string TD_DGTX_CK1 { get; set; }
        public string TD_DGTX_GK2 { get; set; }
        public string TD_DGTX_CK2 { get; set; }
        public string KH_DGTX_GK1 { get; set; }
        public string KH_DGTX_CK1 { get; set; }
        public string KH_DGTX_GK2 { get; set; }
        public string KH_DGTX_CK2 { get; set; }
        public Nullable<int> KH_DIEM_GK1 { get; set; }
        public Nullable<int> KH_DIEM_CK1 { get; set; }
        public Nullable<int> KH_DIEM_GK2 { get; set; }
        public Nullable<int> KH_DIEM_CK2 { get; set; }
        public string LD_DGTX_GK1 { get; set; }
        public string LD_DGTX_CK1 { get; set; }
        public string LD_DGTX_GK2 { get; set; }
        public string LD_DGTX_CK2 { get; set; }
        public Nullable<int> LD_DIEM_GK1 { get; set; }
        public Nullable<int> LD_DIEM_CK1 { get; set; }
        public Nullable<int> LD_DIEM_GK2 { get; set; }
        public Nullable<int> LD_DIEM_CK2 { get; set; }
        public string KT_DGTX_GK1 { get; set; }
        public string KT_DGTX_CK1 { get; set; }
        public string KT_DGTX_GK2 { get; set; }
        public string KT_DGTX_CK2 { get; set; }
        public string NL_TPVTQ_GK1 { get; set; }
        public string NL_TPVTQ_CK1 { get; set; }
        public string NL_TPVTQ_GK2 { get; set; }
        public string NL_TPVTQ_CK2 { get; set; }
        public string NL_HT_GK1 { get; set; }
        public string NL_HT_CK1 { get; set; }
        public string NL_HT_GK2 { get; set; }
        public string NL_HT_CK2 { get; set; }
        public string NL_THGQVD_GK1 { get; set; }
        public string NL_THGQVD_CK1 { get; set; }
        public string NL_THGQVD_GK2 { get; set; }
        public string NL_THGQVD_CK2 { get; set; }
        public string PC_CHCL_GK1 { get; set; }
        public string PC_CHCL_CK1 { get; set; }
        public string PC_CHCL_GK2 { get; set; }
        public string PC_CHCL_CK2 { get; set; }
        public string PC_TTTN_GK1 { get; set; }
        public string PC_TTTN_CK1 { get; set; }
        public string PC_TTTN_GK2 { get; set; }
        public string PC_TTTN_CK2 { get; set; }
        public string PC_TTKL_GK1 { get; set; }
        public string PC_TTKL_CK1 { get; set; }
        public string PC_TTKL_GK2 { get; set; }
        public string PC_TTKL_CK2 { get; set; }
        public string PC_DKYT_GK1 { get; set; }
        public string PC_DKYT_CK1 { get; set; }
        public string PC_DKYT_GK2 { get; set; }
        public string PC_DKYT_CK2 { get; set; }
        public Nullable<bool> IS_KHEN_THUONG_CUOI_NAM { get; set; }
        public Nullable<bool> IS_KHEN_THUONG_DOT_XUAT { get; set; }
        public Nullable<bool> IS_HOAN_THANH_CHUONG_TRINH_LOP_HOC { get; set; }
        public Nullable<bool> IS_HOAN_THANH_CHUONG_TRINH_TIEU_HOC { get; set; }
        public Nullable<int> IS_LEN_LOP { get; set; }
        public string GHI_CHU_GK1 { get; set; }
        public string GHI_CHU_CK1 { get; set; }
        public string GHI_CHU_GK2 { get; set; }
        public string GHI_CHU_CK2 { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<decimal> NGUOI_TAO { get; set; }
        public Nullable<decimal> NGUOI_SUA { get; set; }
    
        public virtual DM_CAP_HOC DM_CAP_HOC { get; set; }
        public virtual HOC_SINH HOC_SINH { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual NAM_HOC NAM_HOC { get; set; }
        public virtual PHONG_GD PHONG_GD { get; set; }
        public virtual SO_GD SO_GD { get; set; }
        public virtual TRUONG TRUONG { get; set; }
    }
}
