//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONG_KET
    {
        public decimal ID { get; set; }
        public Nullable<int> MA_NAM_HOC { get; set; }
        public string MA_SO_GD { get; set; }
        public Nullable<decimal> ID_PHONG_GD { get; set; }
        public string MA_PHONG_GD { get; set; }
        public Nullable<decimal> ID_TRUONG { get; set; }
        public string MA_TRUONG { get; set; }
        public string MA_CAP_HOC { get; set; }
        public string MA_KHOI { get; set; }
        public Nullable<decimal> ID_LOP { get; set; }
        public string MA_LOP { get; set; }
        public Nullable<decimal> ID_HOC_SINH { get; set; }
        public string MA_HOC_SINH { get; set; }
        public Nullable<decimal> DIEM_TONG_KET_KY1 { get; set; }
        public string MA_HOC_LUC_KY1 { get; set; }
        public string MA_HANH_KIEM_KY1 { get; set; }
        public string MA_DANH_HIEU_KY1 { get; set; }
        public Nullable<int> SO_NGAY_NGHI_KY1 { get; set; }
        public string NHAN_XET_K1 { get; set; }
        public string KHEN_THUONG_K1 { get; set; }
        public string KY_LUAT_K1 { get; set; }
        public Nullable<decimal> DIEM_TONG_KET_KY2 { get; set; }
        public string MA_HOC_LUC_KY2 { get; set; }
        public string MA_HANH_KIEM_KY2 { get; set; }
        public string MA_DANH_HIEU_KY2 { get; set; }
        public Nullable<int> SO_NGAY_NGHI_KY2 { get; set; }
        public string NHAN_XET_K2 { get; set; }
        public string KHEN_THUONG_K2 { get; set; }
        public string KY_LUAT_K2 { get; set; }
        public Nullable<decimal> DIEM_TONG_KET_CN { get; set; }
        public string MA_HOC_LUC_CN { get; set; }
        public string MA_HANH_KIEM_CN { get; set; }
        public string MA_DANH_HIEU_CN { get; set; }
        public Nullable<decimal> DIEM_TONG_KET_CN_TTL { get; set; }
        public string MA_HOC_LUC_CN_TTL { get; set; }
        public string MA_HANH_KIEM_CN_TTL { get; set; }
        public string MA_DANH_HIEU_CN_TTL { get; set; }
        public Nullable<int> SO_NGAY_NGHI_CN { get; set; }
        public string NHAN_XET_CN { get; set; }
        public string KHEN_THUONG_CN { get; set; }
        public string KY_LUAT_CN { get; set; }
        public Nullable<int> IS_LEN_LOP { get; set; }
        public Nullable<int> IS_REN_LUYEN_LAI { get; set; }
        public Nullable<int> IS_DU_XET_TOT_NGHIEP { get; set; }
        public Nullable<int> IS_TOT_NGHIEP { get; set; }
        public string MA_LOAI_TOT_NGHIEP { get; set; }
        public Nullable<decimal> DIEM_K1_M1 { get; set; }
        public Nullable<decimal> DIEM_K2_M1 { get; set; }
        public Nullable<decimal> DIEM_CN_M1 { get; set; }
        public Nullable<decimal> DIEM_K1_M2 { get; set; }
        public Nullable<decimal> DIEM_K2_M2 { get; set; }
        public Nullable<decimal> DIEM_CN_M2 { get; set; }
        public Nullable<decimal> DIEM_K1_M3 { get; set; }
        public Nullable<decimal> DIEM_K2_M3 { get; set; }
        public Nullable<decimal> DIEM_CN_M3 { get; set; }
        public Nullable<decimal> DIEM_K1_M4 { get; set; }
        public Nullable<decimal> DIEM_K2_M4 { get; set; }
        public Nullable<decimal> DIEM_CN_M4 { get; set; }
        public Nullable<decimal> DIEM_K1_M5 { get; set; }
        public Nullable<decimal> DIEM_K2_M5 { get; set; }
        public Nullable<decimal> DIEM_CN_M5 { get; set; }
        public Nullable<decimal> DIEM_K1_M6 { get; set; }
        public Nullable<decimal> DIEM_K2_M6 { get; set; }
        public Nullable<decimal> DIEM_CN_M6 { get; set; }
        public Nullable<decimal> DIEM_K1_M7 { get; set; }
        public Nullable<decimal> DIEM_K2_M7 { get; set; }
        public Nullable<decimal> DIEM_CN_M7 { get; set; }
        public Nullable<decimal> DIEM_K1_M8 { get; set; }
        public Nullable<decimal> DIEM_K2_M8 { get; set; }
        public Nullable<decimal> DIEM_CN_M8 { get; set; }
        public Nullable<decimal> DIEM_K1_M9 { get; set; }
        public Nullable<decimal> DIEM_K2_M9 { get; set; }
        public Nullable<decimal> DIEM_CN_M9 { get; set; }
        public Nullable<decimal> DIEM_K1_M10 { get; set; }
        public Nullable<decimal> DIEM_K2_M10 { get; set; }
        public Nullable<decimal> DIEM_CN_M10 { get; set; }
        public Nullable<decimal> DIEM_K1_M11 { get; set; }
        public Nullable<decimal> DIEM_K2_M11 { get; set; }
        public Nullable<decimal> DIEM_CN_M11 { get; set; }
        public Nullable<decimal> DIEM_K1_M12 { get; set; }
        public Nullable<decimal> DIEM_K2_M12 { get; set; }
        public Nullable<decimal> DIEM_CN_M12 { get; set; }
        public Nullable<decimal> DIEM_K1_M13 { get; set; }
        public Nullable<decimal> DIEM_K2_M13 { get; set; }
        public Nullable<decimal> DIEM_CN_M13 { get; set; }
        public Nullable<decimal> DIEM_K1_M14 { get; set; }
        public Nullable<decimal> DIEM_K2_M14 { get; set; }
        public Nullable<decimal> DIEM_CN_M14 { get; set; }
        public Nullable<decimal> DIEM_K1_M15 { get; set; }
        public Nullable<decimal> DIEM_K2_M15 { get; set; }
        public Nullable<decimal> DIEM_CN_M15 { get; set; }
        public Nullable<decimal> DIEM_K1_M16 { get; set; }
        public Nullable<decimal> DIEM_K2_M16 { get; set; }
        public Nullable<decimal> DIEM_CN_M16 { get; set; }
        public Nullable<decimal> DIEM_K1_M17 { get; set; }
        public Nullable<decimal> DIEM_K2_M17 { get; set; }
        public Nullable<decimal> DIEM_CN_M17 { get; set; }
        public Nullable<decimal> DIEM_K1_M18 { get; set; }
        public Nullable<decimal> DIEM_K2_M18 { get; set; }
        public Nullable<decimal> DIEM_CN_M18 { get; set; }
        public Nullable<decimal> DIEM_K1_M19 { get; set; }
        public Nullable<decimal> DIEM_K2_M19 { get; set; }
        public Nullable<decimal> DIEM_CN_M19 { get; set; }
        public Nullable<decimal> DIEM_K1_M20 { get; set; }
        public Nullable<decimal> DIEM_K2_M20 { get; set; }
        public Nullable<decimal> DIEM_CN_M20 { get; set; }
        public Nullable<decimal> DIEM_K1_M1_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M1_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M1_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M2_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M2_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M2_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M3_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M3_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M3_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M4_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M4_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M4_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M5_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M5_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M5_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M6_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M6_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M6_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M7_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M7_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M7_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M8_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M8_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M8_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M9_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M9_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M9_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M10_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M10_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M10_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M11_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M11_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M11_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M12_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M12_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M12_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M13_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M13_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M13_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M14_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M14_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M14_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M15_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M15_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M15_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M16_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M16_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M16_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M17_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M17_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M17_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M18_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M18_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M18_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M19_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M19_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M19_TTL { get; set; }
        public Nullable<decimal> DIEM_K1_M20_TTL { get; set; }
        public Nullable<decimal> DIEM_K2_M20_TTL { get; set; }
        public Nullable<decimal> DIEM_CN_M20_TTL { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public Nullable<decimal> NGUOI_TAO { get; set; }
        public Nullable<decimal> NGUOI_SUA { get; set; }
    
        public virtual DM_CAP_HOC DM_CAP_HOC { get; set; }
        public virtual HOC_SINH HOC_SINH { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual NAM_HOC NAM_HOC { get; set; }
        public virtual PHONG_GD PHONG_GD { get; set; }
        public virtual SO_GD SO_GD { get; set; }
        public virtual TRUONG TRUONG { get; set; }
    }
}
